/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitesRouteImport } from './routes/activites'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as CollegeRouteImport } from './routes/college'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DemandeVisiteRouteImport } from './routes/demande-visite'
import { Route as LyceeRouteImport } from './routes/lycee'
import { Route as MaternelleRouteImport } from './routes/maternelle'
import { Route as NotreEcoleRouteImport } from './routes/notre-ecole'
import { Route as PedagogieRouteImport } from './routes/pedagogie'
import { Route as PrimaireRouteImport } from './routes/primaire'
import { Route as VieScolaireRouteImport } from './routes/vie-scolaire'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitesRoute = ActivitesRouteImport.update({
  id: '/activites',
  path: '/activites',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeRoute = CollegeRouteImport.update({
  id: '/college',
  path: '/college',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandeVisiteRoute = DemandeVisiteRouteImport.update({
  id: '/demande-visite',
  path: '/demande-visite',
  getParentRoute: () => rootRouteImport,
} as any)
const LyceeRoute = LyceeRouteImport.update({
  id: '/lycee',
  path: '/lycee',
  getParentRoute: () => rootRouteImport,
} as any)
const MaternelleRoute = MaternelleRouteImport.update({
  id: '/maternelle',
  path: '/maternelle',
  getParentRoute: () => rootRouteImport,
} as any)
const NotreEcoleRoute = NotreEcoleRouteImport.update({
  id: '/notre-ecole',
  path: '/notre-ecole',
  getParentRoute: () => rootRouteImport,
} as any)
const PedagogieRoute = PedagogieRouteImport.update({
  id: '/pedagogie',
  path: '/pedagogie',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimaireRoute = PrimaireRouteImport.update({
  id: '/primaire',
  path: '/primaire',
  getParentRoute: () => rootRouteImport,
} as any)
const VieScolaireRoute = VieScolaireRouteImport.update({
  id: '/vie-scolaire',
  path: '/vie-scolaire',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activites': typeof ActivitesRoute
  '/actualites': typeof ActualitesRoute
  '/admissions': typeof AdmissionsRoute
  '/college': typeof CollegeRoute
  '/contact': typeof ContactRoute
  '/demande-visite': typeof DemandeVisiteRoute
  '/lycee': typeof LyceeRoute
  '/maternelle': typeof MaternelleRoute
  '/notre-ecole': typeof NotreEcoleRoute
  '/pedagogie': typeof PedagogieRoute
  '/primaire': typeof PrimaireRoute
  '/vie-scolaire': typeof VieScolaireRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activites': typeof ActivitesRoute
  '/actualites': typeof ActualitesRoute
  '/admissions': typeof AdmissionsRoute
  '/college': typeof CollegeRoute
  '/contact': typeof ContactRoute
  '/demande-visite': typeof DemandeVisiteRoute
  '/lycee': typeof LyceeRoute
  '/maternelle': typeof MaternelleRoute
  '/notre-ecole': typeof NotreEcoleRoute
  '/pedagogie': typeof PedagogieRoute
  '/primaire': typeof PrimaireRoute
  '/vie-scolaire': typeof VieScolaireRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activites': typeof ActivitesRoute
  '/actualites': typeof ActualitesRoute
  '/admissions': typeof AdmissionsRoute
  '/college': typeof CollegeRoute
  '/contact': typeof ContactRoute
  '/demande-visite': typeof DemandeVisiteRoute
  '/lycee': typeof LyceeRoute
  '/maternelle': typeof MaternelleRoute
  '/notre-ecole': typeof NotreEcoleRoute
  '/pedagogie': typeof PedagogieRoute
  '/primaire': typeof PrimaireRoute
  '/vie-scolaire': typeof VieScolaireRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activites'
    | '/actualites'
    | '/admissions'
    | '/college'
    | '/contact'
    | '/demande-visite'
    | '/lycee'
    | '/maternelle'
    | '/notre-ecole'
    | '/pedagogie'
    | '/primaire'
    | '/vie-scolaire'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activites'
    | '/actualites'
    | '/admissions'
    | '/college'
    | '/contact'
    | '/demande-visite'
    | '/lycee'
    | '/maternelle'
    | '/notre-ecole'
    | '/pedagogie'
    | '/primaire'
    | '/vie-scolaire'
  id:
    | '__root__'
    | '/'
    | '/activites'
    | '/actualites'
    | '/admissions'
    | '/college'
    | '/contact'
    | '/demande-visite'
    | '/lycee'
    | '/maternelle'
    | '/notre-ecole'
    | '/pedagogie'
    | '/primaire'
    | '/vie-scolaire'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitesRoute: typeof ActivitesRoute
  ActualitesRoute: typeof ActualitesRoute
  AdmissionsRoute: typeof AdmissionsRoute
  CollegeRoute: typeof CollegeRoute
  ContactRoute: typeof ContactRoute
  DemandeVisiteRoute: typeof DemandeVisiteRoute
  LyceeRoute: typeof LyceeRoute
  MaternelleRoute: typeof MaternelleRoute
  NotreEcoleRoute: typeof NotreEcoleRoute
  PedagogieRoute: typeof PedagogieRoute
  PrimaireRoute: typeof PrimaireRoute
  VieScolaireRoute: typeof VieScolaireRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activites': {
      id: '/activites'
      path: '/activites'
      fullPath: '/activites'
      preLoaderRoute: typeof ActivitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college': {
      id: '/college'
      path: '/college'
      fullPath: '/college'
      preLoaderRoute: typeof CollegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demande-visite': {
      id: '/demande-visite'
      path: '/demande-visite'
      fullPath: '/demande-visite'
      preLoaderRoute: typeof DemandeVisiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lycee': {
      id: '/lycee'
      path: '/lycee'
      fullPath: '/lycee'
      preLoaderRoute: typeof LyceeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maternelle': {
      id: '/maternelle'
      path: '/maternelle'
      fullPath: '/maternelle'
      preLoaderRoute: typeof MaternelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notre-ecole': {
      id: '/notre-ecole'
      path: '/notre-ecole'
      fullPath: '/notre-ecole'
      preLoaderRoute: typeof NotreEcoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedagogie': {
      id: '/pedagogie'
      path: '/pedagogie'
      fullPath: '/pedagogie'
      preLoaderRoute: typeof PedagogieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primaire': {
      id: '/primaire'
      path: '/primaire'
      fullPath: '/primaire'
      preLoaderRoute: typeof PrimaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vie-scolaire': {
      id: '/vie-scolaire'
      path: '/vie-scolaire'
      fullPath: '/vie-scolaire'
      preLoaderRoute: typeof VieScolaireRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitesRoute: ActivitesRoute,
  ActualitesRoute: ActualitesRoute,
  AdmissionsRoute: AdmissionsRoute,
  CollegeRoute: CollegeRoute,
  ContactRoute: ContactRoute,
  DemandeVisiteRoute: DemandeVisiteRoute,
  LyceeRoute: LyceeRoute,
  MaternelleRoute: MaternelleRoute,
  NotreEcoleRoute: NotreEcoleRoute,
  PedagogieRoute: PedagogieRoute,
  PrimaireRoute: PrimaireRoute,
  VieScolaireRoute: VieScolaireRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
